FROM ubuntu:22.04

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y wget libc6-i386 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://www.pjrc.com/teensy/hid_listen && \
    chmod +x hid_listen

CMD /hid_listen
