version: '3'
services:
  app:
    image: goropikari/qmkfm:0.23.2
    volumes:
      - /dev:/dev  # マイコンに flash するために mount する
      - ../keyboards:/home/vscode/qmk_firmware/keyboards:cached
      - ../build:/home/vscode/qmk_firmware/.build:cached
      - ../:/home/vscode/miniEC
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: /bin/sh -c "sleep infinity"
